In [1]:
import sys
import os
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)

# 현재 노트북 파일의 경로를 기준으로 프로젝트 루트 경로를 계산
project_root = os.path.abspath(os.path.join(os.getcwd(), '..', '..', '..', '..'))

# sys.path에 프로젝트 루트 경로가 없으면 추가
if project_root not in sys.path:
  sys.path.append(project_root)

In [2]:
from src.data.db_handler import DBHandler

db_handler = DBHandler(db_name="data_lake")

df = db_handler.fetch_data(table_name="kr_stock_asking_price")

column_index = df.columns

df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 87 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    200 non-null    int64
 1   ticker                200 non-null    object
 2   aspr_acpt_hour        200 non-null    object
 3   askp1                 200 non-null    object
 4   askp2                 200 non-null    object
 5   askp3                 200 non-null    object
 6   askp4                 200 non-null    object
 7   askp5                 200 non-null    object
 8   askp6                 200 non-null    object
 9   askp7                 200 non-null    object
 10  askp8                 200 non-null    object
 11  askp9                 200 non-null    object
 12  askp10                200 non-null    object
 13  bidp1                 200 non-null    object
 14  bidp2                 200 non-null    object
 15  bidp3                 200 non-null    object
 16  bidp4                 200 non-null    object
 17  bidp5                 200 non-null    object
 18  bidp6                 200 non-null    object
 19  bidp7                 200 non-null    object
 20  bidp8                 200 non-null    object
 21  bidp9                 200 non-null    object
 22  bidp10                200 non-null    object
 23  askp_rsqn1            200 non-null    object
 24  askp_rsqn2            200 non-null    object
 25  askp_rsqn3            200 non-null    object
 26  askp_rsqn4            200 non-null    object
 27  askp_rsqn5            200 non-null    object
 28  askp_rsqn6            200 non-null    object
 29  askp_rsqn7            200 non-null    object
 30  askp_rsqn8            200 non-null    object
 31  askp_rsqn9            200 non-null    object
 32  askp_rsqn10           200 non-null    object
 33  bidp_rsqn1            200 non-null    object
 34  bidp_rsqn2            200 non-null    object
 35  bidp_rsqn3            200 non-null    object
 36  bidp_rsqn4            200 non-null    object
 37  bidp_rsqn5            200 non-null    object
 38  bidp_rsqn6            200 non-null    object
 39  bidp_rsqn7            200 non-null    object
 40  bidp_rsqn8            200 non-null    object
 41  bidp_rsqn9            200 non-null    object
 42  bidp_rsqn10           200 non-null    object
 43  askp_rsqn_icdc1       200 non-null    object
 44  askp_rsqn_icdc2       200 non-null    object
 45  askp_rsqn_icdc3       200 non-null    object
 46  askp_rsqn_icdc4       200 non-null    object
 47  askp_rsqn_icdc5       200 non-null    object
 48  askp_rsqn_icdc6       200 non-null    object
 49  askp_rsqn_icdc7       200 non-null    object
 50  askp_rsqn_icdc8       200 non-null    object
 51  askp_rsqn_icdc9       200 non-null    object
 52  askp_rsqn_icdc10      200 non-null    object
 53  bidp_rsqn_icdc1       200 non-null    object
 54  bidp_rsqn_icdc2       200 non-null    object
 55  bidp_rsqn_icdc3       200 non-null    object
 56  bidp_rsqn_icdc4       200 non-null    object
 57  bidp_rsqn_icdc5       200 non-null    object
 58  bidp_rsqn_icdc6       200 non-null    object
 59  bidp_rsqn_icdc7       200 non-null    object
 60  bidp_rsqn_icdc8       200 non-null    object
 61  bidp_rsqn_icdc9       200 non-null    object
 62  bidp_rsqn_icdc10      200 non-null    object
 63  total_askp_rsqn       200 non-null    object
 64  total_bidp_rsqn       200 non-null    object
 65  total_askp_rsqn_icdc  200 non-null    object
 66  total_bidp_rsqn_icdc  200 non-null    object
 67  ovtm_total_askp_icdc  200 non-null    object
 68  ovtm_total_bidp_icdc  200 non-null    object
 69  ovtm_total_askp_rsqn  200 non-null    object
 70  ovtm_total_bidp_rsqn  200 non-null    object
 71  ntby_aspr_rsqn        200 non-null    object
 72  new_mkop_cls_code     200 non-null    object
 73  antc_mkop_cls_code    200 non-null    object
 74  stck_prpr             200 non-null    object
 75  stck_oprc             200 non-null    object
 76  stck_hgpr             200 non-null    object
 77  stck_lwpr             200 non-null    object
 78  stck_sdpr             200 non-null    object
 79  antc_cnpr             200 non-null    object
 80  antc_cntg_vrss_sign   200 non-null    object
 81  antc_cntg_vrss        200 non-null    object
 82  antc_cntg_prdy_ctrt   200 non-null    object
 83  antc_vol              200 non-null    object
 84  stck_shrn_iscd        200 non-null    object
 85  vi_cls_code           200 non-null    object
 86  updated_at            200 non-null    datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1), int64(1), object(85)
memory usage: 136.1+ KB

,id,ticker,aspr_acpt_hour,askp1,askp2,askp3,askp4,askp5,askp6,askp7,askp8,askp9,askp10,bidp1,bidp2,bidp3,bidp4,bidp5,bidp6,bidp7,bidp8,bidp9,bidp10,askp_rsqn1,askp_rsqn2,askp_rsqn3,askp_rsqn4,askp_rsqn5,askp_rsqn6,askp_rsqn7,askp_rsqn8,askp_rsqn9,askp_rsqn10,bidp_rsqn1,bidp_rsqn2,bidp_rsqn3,bidp_rsqn4,bidp_rsqn5,bidp_rsqn6,bidp_rsqn7,bidp_rsqn8,bidp_rsqn9,bidp_rsqn10,askp_rsqn_icdc1,askp_rsqn_icdc2,askp_rsqn_icdc3,askp_rsqn_icdc4,askp_rsqn_icdc5,askp_rsqn_icdc6,askp_rsqn_icdc7,askp_rsqn_icdc8,askp_rsqn_icdc9,askp_rsqn_icdc10,bidp_rsqn_icdc1,bidp_rsqn_icdc2,bidp_rsqn_icdc3,bidp_rsqn_icdc4,bidp_rsqn_icdc5,bidp_rsqn_icdc6,bidp_rsqn_icdc7,bidp_rsqn_icdc8,bidp_rsqn_icdc9,bidp_rsqn_icdc10,total_askp_rsqn,total_bidp_rsqn,total_askp_rsqn_icdc,total_bidp_rsqn_icdc,ovtm_total_askp_icdc,ovtm_total_bidp_icdc,ovtm_total_askp_rsqn,ovtm_total_bidp_rsqn,ntby_aspr_rsqn,new_mkop_cls_code,antc_mkop_cls_code,stck_prpr,stck_oprc,stck_hgpr,stck_lwpr,stck_sdpr,antc_cnpr,antc_cntg_vrss_sign,antc_cntg_vrss,antc_cntg_prdy_ctrt,antc_vol,stck_shrn_iscd,vi_cls_code,updated_at
0,1,000080,160000,19170,19180,19190,19200,19210,19220,19230,19240,19250,19260,19160,19150,19140,19130,19120,19110,19100,19090,19080,19070,2593,1470,254,181,25,135,3,1174,23,46,298,5086,1207,5708,5010,7074,5596,2932,5652,1119,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,5904,39682,0,0,0,0,19,0,33778,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
1,2,000100,160000,118600,118700,118800,118900,119000,119100,119200,119300,119400,119500,118500,118400,118300,118200,118100,118000,117900,117800,117700,117600,1110,2795,1710,5032,4668,2908,2231,1382,1584,7822,527,848,4620,3904,1700,2827,1878,1154,831,1650,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,31242,19939,0,0,0,0,0,0,-11303,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
2,3,000120,160000,84500,84600,84700,84800,84900,85000,85100,85200,85300,85400,84400,84300,84200,84100,84000,83900,83800,83700,83600,83500,528,260,645,176,10,41,230,170,10,73,340,96,545,477,1899,1709,762,699,216,404,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2143,7147,0,0,0,0,0,1,5004,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
3,4,000150,160000,596000,597000,598000,599000,600000,601000,602000,603000,604000,605000,595000,594000,593000,592000,591000,590000,589000,588000,587000,586000,2847,2613,2392,2000,1843,3653,4486,540,531,2039,443,789,1742,2101,434,2129,481,263,176,3519,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22944,12077,0,0,0,0,0,7,-10867,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
4,5,000210,160000,37550,37600,37650,37700,37800,37850,37900,37950,38000,38050,37500,37300,37250,37200,37150,37100,37050,37000,36950,36900,512,221,1153,1,312,9,288,318,8307,5121,180,198,342,1127,818,517,1444,1570,666,144,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,16242,7006,0,0,0,0,418,0,-9236,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,196,450080,160001,51700,51800,51900,52000,52100,52200,52300,52400,52500,52600,51600,51500,51400,51300,51200,51100,51000,50900,50800,50700,2710,2504,2080,3505,1193,2380,2342,279,1412,496,512,1485,925,7365,3453,5840,5287,2415,1418,2369,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,18901,31069,0,0,0,0,0,1,12168,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
196,197,454910,160001,66400,66500,66600,66700,66800,66900,67000,67100,67200,67300,66300,66200,66100,66000,65900,65800,65700,65600,65500,65400,3165,3603,1093,520,688,2408,4986,1356,1674,2663,3266,1039,1560,1252,862,1361,2352,1490,2481,805,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,22156,16468,0,0,0,0,0,169,-5688,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
197,198,456040,160001,58200,58300,58400,58500,58600,58700,58800,58900,59000,59100,58100,58000,57900,57800,57700,57600,57500,57400,57300,57200,32,413,616,530,181,437,264,192,516,165,140,463,348,1032,492,213,248,64,52,175,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3346,3227,0,0,0,0,3,0,-119,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
198,199,457190,160001,45900,45950,46000,46050,46100,46150,46200,46250,46300,46350,45850,45800,45750,45700,45650,45600,45550,45500,45450,45400,356,815,569,622,735,72,1130,211,3998,130,856,269,721,2125,2516,1965,1366,2878,2377,690,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8638,15763,0,0,0,0,0,332,7125,20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00
199,200,489790,160001,59500,59600,59700,59800,59900,60000,60100,60200,60300,60400,59400,59300,59200,59100,59000,58900,58800,58700,58600,58500,728,1844,3071,2157,1949,1763,1144,6910,403,170,3677,8063,9496,10444,5328,7255,7875,3679,2640,5614,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20139,64071,0,0,0,0,0,18,43932,31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-21 18:42:36.840061+00:00

In [3]:
final_cols = column_index[1:]

In [4]:
df[final_cols] = df[final_cols].replace(r'^\s*$', np.nan, regex=True)
df[final_cols] = df[final_cols].replace(['0', 0], np.nan)

# 결측치 개수 계산
missing_value_counts = df[final_cols].isnull().sum()

# 전체 행의 개수 계산
total_rows = len(df[final_cols])

# 결측치 비율 계산
missing_value_percent = ((missing_value_counts / total_rows) * 100).round(2)

# --- 3. 결과 취합 및 출력 ---
missing_df = pd.DataFrame({
  'missing_count': missing_value_counts,
  'missing_percent': missing_value_percent
})

# 결측치가 많은 순서대로 정렬하여 출력
missing_df = missing_df[missing_df['missing_count'] > 0]
missing_df = missing_df.sort_values(by='missing_count', ascending=False)

missing_df

                      missing_count  missing_percent
askp_rsqn_icdc1                 200            100.0
bidp_rsqn_icdc3                 200            100.0
ovtm_total_askp_icdc            200            100.0
total_bidp_rsqn_icdc            200            100.0
total_askp_rsqn_icdc            200            100.0
bidp_rsqn_icdc10                200            100.0
bidp_rsqn_icdc9                 200            100.0
bidp_rsqn_icdc8                 200            100.0
bidp_rsqn_icdc7                 200            100.0
bidp_rsqn_icdc6                 200            100.0
bidp_rsqn_icdc5                 200            100.0
askp_rsqn_icdc2                 200            100.0
bidp_rsqn_icdc4                 200            100.0
bidp_rsqn_icdc2                 200            100.0
bidp_rsqn_icdc1                 200            100.0
askp_rsqn_icdc10                200            100.0
askp_rsqn_icdc9                 200            100.0
askp_rsqn_icdc8                 200            100.0
askp_rsqn_icdc7                 200            100.0
askp_rsqn_icdc6                 200            100.0
askp_rsqn_icdc5                 200            100.0
askp_rsqn_icdc4                 200            100.0
askp_rsqn_icdc3                 200            100.0
ovtm_total_bidp_icdc            198             99.0
ovtm_total_bidp_rsqn            119             59.5
ovtm_total_askp_rsqn            113             56.5

In [5]:
missing_cols = missing_df[missing_df['missing_percent'] >= 50].index.to_list()

final_cols = [col for col in final_cols if col not in missing_cols]

print(f"결측 컬럼 : {missing_cols}")

print(f"[원본 컬럼 : {len(column_index)-1}] - [결측 컬럼 : {len(missing_cols)}] = [후보 컬럼 : {len(final_cols)}]")

결측 컬럼 : ['askp_rsqn_icdc1', 'bidp_rsqn_icdc3', 'ovtm_total_askp_icdc', 'total_bidp_rsqn_icdc', 'total_askp_rsqn_icdc', 'bidp_rsqn_icdc10', 'bidp_rsqn_icdc9', 'bidp_rsqn_icdc8', 'bidp_rsqn_icdc7', 'bidp_rsqn_icdc6', 'bidp_rsqn_icdc5', 'askp_rsqn_icdc2', 'bidp_rsqn_icdc4', 'bidp_rsqn_icdc2', 'bidp_rsqn_icdc1', 'askp_rsqn_icdc10', 'askp_rsqn_icdc9', 'askp_rsqn_icdc8', 'askp_rsqn_icdc7', 'askp_rsqn_icdc6', 'askp_rsqn_icdc5', 'askp_rsqn_icdc4', 'askp_rsqn_icdc3', 'ovtm_total_bidp_icdc', 'ovtm_total_bidp_rsqn', 'ovtm_total_askp_rsqn']
[원본 컬럼 : 86] - [결측 컬럼 : 26] = [후보 컬럼 : 60]

In [6]:
nunique_counts = df[final_cols].nunique()

# 전체 행의 개수 계산
total_rows = len(df[final_cols])

# 결측치 비율 계산
nunique_value_percent = ((nunique_counts / total_rows) * 100).round(2)

unique_cols = nunique_counts[nunique_counts == 1].index.tolist()

# --- 3. 결과 취합 및 출력 ---
nunique_df = pd.DataFrame({
  'nunique_count': nunique_counts,
  'nunique_percent': nunique_value_percent
})

# 결측치가 많은 순서대로 정렬하여 출력
nunique_df = nunique_df[nunique_df['nunique_count'] > 1]
nunique_df = nunique_df.sort_values(by='nunique_count', ascending=False)

nunique_df

                   nunique_count  nunique_percent
ticker                       200            100.0
total_bidp_rsqn              200            100.0
ntby_aspr_rsqn               200            100.0
total_askp_rsqn              200            100.0
bidp_rsqn6                   196             98.0
bidp_rsqn8                   195             97.5
bidp_rsqn9                   195             97.5
bidp_rsqn7                   194             97.0
bidp_rsqn5                   194             97.0
bidp8                        193             96.5
askp10                       193             96.5
bidp1                        193             96.5
bidp2                        193             96.5
bidp_rsqn3                   193             96.5
bidp5                        193             96.5
bidp6                        193             96.5
bidp7                        193             96.5
askp_rsqn5                   193             96.5
bidp9                        193             96.5
bidp10                       193             96.5
askp4                        192             96.0
askp1                        192             96.0
askp2                        192             96.0
askp8                        192             96.0
askp5                        192             96.0
askp6                        192             96.0
askp9                        192             96.0
askp7                        192             96.0
bidp3                        192             96.0
askp_rsqn2                   191             95.5
bidp4                        191             95.5
askp3                        191             95.5
bidp_rsqn4                   190             95.0
askp_rsqn3                   190             95.0
bidp_rsqn10                  190             95.0
askp_rsqn1                   190             95.0
askp_rsqn6                   189             94.5
askp_rsqn4                   189             94.5
askp_rsqn8                   187             93.5
askp_rsqn10                  184             92.0
bidp_rsqn1                   184             92.0
askp_rsqn9                   182             91.0
bidp_rsqn2                   181             90.5
askp_rsqn7                   180             90.0
aspr_acpt_hour                 2              1.0
new_mkop_cls_code              2              1.0

In [7]:
final_cols = [col for col in final_cols if col not in unique_cols]

print(f"유니크 컬럼 : {unique_cols}")

print(f"[원본 컬럼 : {len(column_index)-1}] - [결측 컬럼 : {len(missing_cols)}] - [유니크 컬럼 : {len(unique_cols)}] = [후보 컬럼 : {len(final_cols)}]")

유니크 컬럼 : ['antc_mkop_cls_code', 'stck_prpr', 'stck_oprc', 'stck_hgpr', 'stck_lwpr', 'stck_sdpr', 'antc_cnpr', 'antc_cntg_vrss_sign', 'antc_cntg_vrss', 'antc_cntg_prdy_ctrt', 'antc_vol', 'stck_shrn_iscd', 'vi_cls_code', 'updated_at']
[원본 컬럼 : 86] - [결측 컬럼 : 26] - [유니크 컬럼 : 14] = [후보 컬럼 : 46]

In [8]:
df[final_cols]

,ticker,aspr_acpt_hour,askp1,askp2,askp3,askp4,askp5,askp6,askp7,askp8,askp9,askp10,bidp1,bidp2,bidp3,bidp4,bidp5,bidp6,bidp7,bidp8,bidp9,bidp10,askp_rsqn1,askp_rsqn2,askp_rsqn3,askp_rsqn4,askp_rsqn5,askp_rsqn6,askp_rsqn7,askp_rsqn8,askp_rsqn9,askp_rsqn10,bidp_rsqn1,bidp_rsqn2,bidp_rsqn3,bidp_rsqn4,bidp_rsqn5,bidp_rsqn6,bidp_rsqn7,bidp_rsqn8,bidp_rsqn9,bidp_rsqn10,total_askp_rsqn,total_bidp_rsqn,ntby_aspr_rsqn,new_mkop_cls_code
0,000080,160000,19170,19180,19190,19200,19210,19220,19230,19240,19250,19260,19160,19150,19140,19130,19120,19110,19100,19090,19080,19070,2593,1470,254,181,25,135,3,1174,23,46,298,5086,1207,5708,5010,7074,5596,2932,5652,1119,5904,39682,33778,31
1,000100,160000,118600,118700,118800,118900,119000,119100,119200,119300,119400,119500,118500,118400,118300,118200,118100,118000,117900,117800,117700,117600,1110,2795,1710,5032,4668,2908,2231,1382,1584,7822,527,848,4620,3904,1700,2827,1878,1154,831,1650,31242,19939,-11303,31
2,000120,160000,84500,84600,84700,84800,84900,85000,85100,85200,85300,85400,84400,84300,84200,84100,84000,83900,83800,83700,83600,83500,528,260,645,176,10,41,230,170,10,73,340,96,545,477,1899,1709,762,699,216,404,2143,7147,5004,20
3,000150,160000,596000,597000,598000,599000,600000,601000,602000,603000,604000,605000,595000,594000,593000,592000,591000,590000,589000,588000,587000,586000,2847,2613,2392,2000,1843,3653,4486,540,531,2039,443,789,1742,2101,434,2129,481,263,176,3519,22944,12077,-10867,31
4,000210,160000,37550,37600,37650,37700,37800,37850,37900,37950,38000,38050,37500,37300,37250,37200,37150,37100,37050,37000,36950,36900,512,221,1153,1,312,9,288,318,8307,5121,180,198,342,1127,818,517,1444,1570,666,144,16242,7006,-9236,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,450080,160001,51700,51800,51900,52000,52100,52200,52300,52400,52500,52600,51600,51500,51400,51300,51200,51100,51000,50900,50800,50700,2710,2504,2080,3505,1193,2380,2342,279,1412,496,512,1485,925,7365,3453,5840,5287,2415,1418,2369,18901,31069,12168,31
196,454910,160001,66400,66500,66600,66700,66800,66900,67000,67100,67200,67300,66300,66200,66100,66000,65900,65800,65700,65600,65500,65400,3165,3603,1093,520,688,2408,4986,1356,1674,2663,3266,1039,1560,1252,862,1361,2352,1490,2481,805,22156,16468,-5688,31
197,456040,160001,58200,58300,58400,58500,58600,58700,58800,58900,59000,59100,58100,58000,57900,57800,57700,57600,57500,57400,57300,57200,32,413,616,530,181,437,264,192,516,165,140,463,348,1032,492,213,248,64,52,175,3346,3227,-119,20
198,457190,160001,45900,45950,46000,46050,46100,46150,46200,46250,46300,46350,45850,45800,45750,45700,45650,45600,45550,45500,45450,45400,356,815,569,622,735,72,1130,211,3998,130,856,269,721,2125,2516,1965,1366,2878,2377,690,8638,15763,7125,20
199,489790,160001,59500,59600,59700,59800,59900,60000,60100,60200,60300,60400,59400,59300,59200,59100,59000,58900,58800,58700,58600,58500,728,1844,3071,2157,1949,1763,1144,6910,403,170,3677,8063,9496,10444,5328,7255,7875,3679,2640,5614,20139,64071,43932,31

In [9]:
print(final_cols)

['ticker', 'aspr_acpt_hour', 'askp1', 'askp2', 'askp3', 'askp4', 'askp5', 'askp6', 'askp7', 'askp8', 'askp9', 'askp10', 'bidp1', 'bidp2', 'bidp3', 'bidp4', 'bidp5', 'bidp6', 'bidp7', 'bidp8', 'bidp9', 'bidp10', 'askp_rsqn1', 'askp_rsqn2', 'askp_rsqn3', 'askp_rsqn4', 'askp_rsqn5', 'askp_rsqn6', 'askp_rsqn7', 'askp_rsqn8', 'askp_rsqn9', 'askp_rsqn10', 'bidp_rsqn1', 'bidp_rsqn2', 'bidp_rsqn3', 'bidp_rsqn4', 'bidp_rsqn5', 'bidp_rsqn6', 'bidp_rsqn7', 'bidp_rsqn8', 'bidp_rsqn9', 'bidp_rsqn10', 'total_askp_rsqn', 'total_bidp_rsqn', 'ntby_aspr_rsqn', 'new_mkop_cls_code']

| 컬럼명 | 한글컬럼명 | 중요도 | 이유 |
| :--- | :--- | :--- | :--- |
| `ticker` | 티커(종목 코드) | **필수** | 어떤 종목의 호가 데이터인지를 특정하는 핵심 식별자입니다. |
| `aspr_acpt_hour` | 호가수신시각 | **필수** | 호가 정보가 기록된 시점(HHMMSS)으로, 시계열 분석에 반드시 필요합니다. |
| `askp1` | 매도호가1 | **필수** | 현재 가장 낮은 매도 가격으로, 매수자가 즉시 체결할 수 있는 최적 가격입니다. |
| `askp2` | 매도호가2 | **상** | 매도호가1 위의 저항 수준을 파악하는 데 사용되는 2순위 매도 가격입니다. |
| `askp3` | 매도호가3 | **상** | 시장의 매도 깊이(Market Depth)를 보여주는 3순위 매도 가격입니다. |
| `askp4` | 매도호가4 | **중** | 더 깊은 수준의 매도 압력을 파악하기 위한 4순위 매도 가격입니다. |
| `askp5` | 매도호가5 | **중** | 더 깊은 수준의 매도 압력을 파악하기 위한 5순위 매도 가격입니다. |
| `askp6` | 매도호가6 | **중** | 더 깊은 수준의 매도 압력을 파악하기 위한 6순위 매도 가격입니다. |
| `askp7` | 매도호가7 | **중** | 더 깊은 수준의 매도 압력을 파악하기 위한 7순위 매도 가격입니다. |
| `askp8` | 매도호가8 | **중** | 더 깊은 수준의 매도 압력을 파악하기 위한 8순위 매도 가격입니다. |
| `askp9` | 매도호가9 | **중** | 더 깊은 수준의 매도 압력을 파악하기 위한 9순위 매도 가격입니다. |
| `askp10` | 매도호가10 | **중** | 가장 깊은 수준의 매도 압력을 보여주는 10순위 매도 가격입니다. |
| `bidp1` | 매수호가1 | **필수** | 현재 가장 높은 매수 가격으로, 매도자가 즉시 체결할 수 있는 최적 가격입니다. |
| `bidp2` | 매수호가2 | **상** | 매수호가1 아래의 지지 수준을 파악하는 데 사용되는 2순위 매수 가격입니다. |
| `bidp3` | 매수호가3 | **상** | 시장의 매수 깊이(Market Depth)를 보여주는 3순위 매수 가격입니다. |
| `bidp4` | 매수호가4 | **중** | 더 깊은 수준의 매수 지지력을 파악하기 위한 4순위 매수 가격입니다. |
| `bidp5` | 매수호가5 | **중** | 더 깊은 수준의 매수 지지력을 파악하기 위한 5순위 매수 가격입니다. |
| `bidp6` | 매수호가6 | **중** | 더 깊은 수준의 매수 지지력을 파악하기 위한 6순위 매수 가격입니다. |
| `bidp7` | 매수호가7 | **중** | 더 깊은 수준의 매수 지지력을 파악하기 위한 7순위 매수 가격입니다. |
| `bidp8` | 매수호가8 | **중** | 더 깊은 수준의 매수 지지력을 파악하기 위한 8순위 매수 가격입니다. |
| `bidp9` | 매수호가9 | **중** | 더 깊은 수준의 매수 지지력을 파악하기 위한 9순위 매수 가격입니다. |
| `bidp10` | 매수호가10 | **중** | 가장 깊은 수준의 매수 지지력을 보여주는 10순위 매수 가격입니다. |
| `askp_rsqn1` | 매도호가잔량1 | **상** | 최적 매도호가에 쌓여있는 물량으로, 단기 저항의 강도를 나타냅니다. |
| `askp_rsqn2` | 매도호가잔량2 | **중** | 2순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn3` | 매도호가잔량3 | **중** | 3순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn4` | 매도호가잔량4 | **중** | 4순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn5` | 매도호가잔량5 | **중** | 5순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn6` | 매도호가잔량6 | **중** | 6순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn7` | 매도호가잔량7 | **중** | 7순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn8` | 매도호가잔량8 | **중** | 8순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn9` | 매도호가잔량9 | **중** | 9순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `askp_rsqn10` | 매도호가잔량10 | **중** | 10순위 매도호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn1` | 매수호가잔량1 | **상** | 최적 매수호가에 쌓여있는 물량으로, 단기 지지의 강도를 나타냅니다. |
| `bidp_rsqn2` | 매수호가잔량2 | **중** | 2순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn3` | 매수호가잔량3 | **중** | 3순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn4` | 매수호가잔량4 | **중** | 4순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn5` | 매수호가잔량5 | **중** | 5순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn6` | 매수호가잔량6 | **중** | 6순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn7` | 매수호가잔량7 | **중** | 7순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn8` | 매수호가잔량8 | **중** | 8순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn9` | 매수호가잔량9 | **중** | 9순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `bidp_rsqn10` | 매수호가잔량10 | **중** | 10순위 매수호가의 물량으로, 시장 깊이를 구성하는 정보입니다. |
| `total_askp_rsqn`| 총매도호가잔량 | **상** | 전체 매도 잔량의 합으로, 시장의 전반적인 매도 압력을 보여주는 핵심 지표입니다. |
| `total_bidp_rsqn`| 총매수호가잔량 | **상** | 전체 매수 잔량의 합으로, 시장의 전반적인 매수 지지력을 보여주는 핵심 지표입니다. |
| `ntby_aspr_rsqn`| 시간외순매수잔량| **상** | `총매수잔량 - 총매도잔량`으로, 현재 시장의 수급 방향성을 직관적으로 보여주는 파생 피처입니다. |
| `new_mkop_cls_code`| 장구분코드 | **중** | 장전/장중/장후 등 시장 상태를 나타내는 코드로, 시간대별 변동성 패턴 분석에 유용한 컨텍스트를 제공합니다. |

In [10]:
final_cols = [
  'ticker',
  'aspr_acpt_hour',
  'askp1',
  'askp2',
  'askp3',
  'askp4',
  'askp5',
  'askp6',
  'askp7',
  'askp8',
  'askp9',
  'askp10',
  'bidp1',
  'bidp2',
  'bidp3',
  'bidp4',
  'bidp5',
  'bidp6',
  'bidp7',
  'bidp8',
  'bidp9',
  'bidp10',
  'askp_rsqn1',
  'askp_rsqn2',
  'askp_rsqn3',
  'askp_rsqn4',
  'askp_rsqn5',
  'askp_rsqn6',
  'askp_rsqn7',
  'askp_rsqn8',
  'askp_rsqn9',
  'askp_rsqn10',
  'bidp_rsqn1',
  'bidp_rsqn2',
  'bidp_rsqn3',
  'bidp_rsqn4',
  'bidp_rsqn5',
  'bidp_rsqn6',
  'bidp_rsqn7',
  'bidp_rsqn8',
  'bidp_rsqn9',
  'bidp_rsqn10',
  'total_askp_rsqn',
  'total_bidp_rsqn',
  'ntby_aspr_rsqn',
  'new_mkop_cls_code'
]

In [11]:
df[final_cols]

,ticker,aspr_acpt_hour,askp1,askp2,askp3,askp4,askp5,askp6,askp7,askp8,askp9,askp10,bidp1,bidp2,bidp3,bidp4,bidp5,bidp6,bidp7,bidp8,bidp9,bidp10,askp_rsqn1,askp_rsqn2,askp_rsqn3,askp_rsqn4,askp_rsqn5,askp_rsqn6,askp_rsqn7,askp_rsqn8,askp_rsqn9,askp_rsqn10,bidp_rsqn1,bidp_rsqn2,bidp_rsqn3,bidp_rsqn4,bidp_rsqn5,bidp_rsqn6,bidp_rsqn7,bidp_rsqn8,bidp_rsqn9,bidp_rsqn10,total_askp_rsqn,total_bidp_rsqn,ntby_aspr_rsqn,new_mkop_cls_code
0,000080,160000,19170,19180,19190,19200,19210,19220,19230,19240,19250,19260,19160,19150,19140,19130,19120,19110,19100,19090,19080,19070,2593,1470,254,181,25,135,3,1174,23,46,298,5086,1207,5708,5010,7074,5596,2932,5652,1119,5904,39682,33778,31
1,000100,160000,118600,118700,118800,118900,119000,119100,119200,119300,119400,119500,118500,118400,118300,118200,118100,118000,117900,117800,117700,117600,1110,2795,1710,5032,4668,2908,2231,1382,1584,7822,527,848,4620,3904,1700,2827,1878,1154,831,1650,31242,19939,-11303,31
2,000120,160000,84500,84600,84700,84800,84900,85000,85100,85200,85300,85400,84400,84300,84200,84100,84000,83900,83800,83700,83600,83500,528,260,645,176,10,41,230,170,10,73,340,96,545,477,1899,1709,762,699,216,404,2143,7147,5004,20
3,000150,160000,596000,597000,598000,599000,600000,601000,602000,603000,604000,605000,595000,594000,593000,592000,591000,590000,589000,588000,587000,586000,2847,2613,2392,2000,1843,3653,4486,540,531,2039,443,789,1742,2101,434,2129,481,263,176,3519,22944,12077,-10867,31
4,000210,160000,37550,37600,37650,37700,37800,37850,37900,37950,38000,38050,37500,37300,37250,37200,37150,37100,37050,37000,36950,36900,512,221,1153,1,312,9,288,318,8307,5121,180,198,342,1127,818,517,1444,1570,666,144,16242,7006,-9236,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,450080,160001,51700,51800,51900,52000,52100,52200,52300,52400,52500,52600,51600,51500,51400,51300,51200,51100,51000,50900,50800,50700,2710,2504,2080,3505,1193,2380,2342,279,1412,496,512,1485,925,7365,3453,5840,5287,2415,1418,2369,18901,31069,12168,31
196,454910,160001,66400,66500,66600,66700,66800,66900,67000,67100,67200,67300,66300,66200,66100,66000,65900,65800,65700,65600,65500,65400,3165,3603,1093,520,688,2408,4986,1356,1674,2663,3266,1039,1560,1252,862,1361,2352,1490,2481,805,22156,16468,-5688,31
197,456040,160001,58200,58300,58400,58500,58600,58700,58800,58900,59000,59100,58100,58000,57900,57800,57700,57600,57500,57400,57300,57200,32,413,616,530,181,437,264,192,516,165,140,463,348,1032,492,213,248,64,52,175,3346,3227,-119,20
198,457190,160001,45900,45950,46000,46050,46100,46150,46200,46250,46300,46350,45850,45800,45750,45700,45650,45600,45550,45500,45450,45400,356,815,569,622,735,72,1130,211,3998,130,856,269,721,2125,2516,1965,1366,2878,2377,690,8638,15763,7125,20
199,489790,160001,59500,59600,59700,59800,59900,60000,60100,60200,60300,60400,59400,59300,59200,59100,59000,58900,58800,58700,58600,58500,728,1844,3071,2157,1949,1763,1144,6910,403,170,3677,8063,9496,10444,5328,7255,7875,3679,2640,5614,20139,64071,43932,31

In [12]:
final_df = df[final_cols].copy()

# --- 1단계: 날짜 타입 자동 변환 ---
remaining_object_cols = final_df.select_dtypes(include='object').columns.tolist()
for col in remaining_object_cols:
  original_valid_count = final_df[col].count()
  if original_valid_count == 0: continue
  
  for format in ['%Y%m%d', '%Y-%m-%d', '%Y%m', '%Y-%m']:
    date_series = pd.to_datetime(final_df[col], format=format,errors='coerce')
    success_rate = date_series.count() / original_valid_count
    
    if success_rate > 0.95: # 95% 임계값
      final_df[col] = date_series
      break

# --- 2단계: 저비율 카테고리 자동 변환 ---
object_cols = final_df.select_dtypes(include='object').columns.tolist()
for col in object_cols:
  ratio = final_df[col].nunique() / len(final_df[col])
  if ratio < 0.05: # 5% 임계값
    final_df[col] = final_df[col].astype('category')

In [13]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 46 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ticker             200 non-null    object
 1   aspr_acpt_hour     200 non-null    category
 2   askp1              200 non-null    object
 3   askp2              200 non-null    object
 4   askp3              200 non-null    object
 5   askp4              200 non-null    object
 6   askp5              200 non-null    object
 7   askp6              200 non-null    object
 8   askp7              200 non-null    object
 9   askp8              200 non-null    object
 10  askp9              200 non-null    object
 11  askp10             200 non-null    object
 12  bidp1              200 non-null    object
 13  bidp2              200 non-null    object
 14  bidp3              200 non-null    object
 15  bidp4              200 non-null    object
 16  bidp5              200 non-null    object
 17  bidp6              200 non-null    object
 18  bidp7              200 non-null    object
 19  bidp8              200 non-null    object
 20  bidp9              200 non-null    object
 21  bidp10             200 non-null    object
 22  askp_rsqn1         200 non-null    object
 23  askp_rsqn2         200 non-null    object
 24  askp_rsqn3         200 non-null    object
 25  askp_rsqn4         200 non-null    object
 26  askp_rsqn5         200 non-null    object
 27  askp_rsqn6         200 non-null    object
 28  askp_rsqn7         200 non-null    object
 29  askp_rsqn8         200 non-null    object
 30  askp_rsqn9         200 non-null    object
 31  askp_rsqn10        200 non-null    object
 32  bidp_rsqn1         200 non-null    object
 33  bidp_rsqn2         200 non-null    object
 34  bidp_rsqn3         200 non-null    object
 35  bidp_rsqn4         200 non-null    object
 36  bidp_rsqn5         200 non-null    object
 37  bidp_rsqn6         200 non-null    object
 38  bidp_rsqn7         200 non-null    object
 39  bidp_rsqn8         200 non-null    object
 40  bidp_rsqn9         200 non-null    object
 41  bidp_rsqn10        200 non-null    object
 42  total_askp_rsqn    200 non-null    object
 43  total_bidp_rsqn    200 non-null    object
 44  ntby_aspr_rsqn     200 non-null    object
 45  new_mkop_cls_code  200 non-null    category
dtypes: category(2), object(44)
memory usage: 69.5+ KB

| 컬럼명 | 현재 타입 | 적정 타입 | 이유 |
| :--- | :--- | :--- | :--- |
| `ticker` | `object` | `category` | 반복되는 종목 코드는 메모리 효율을 위해 `category`가 가장 적합합니다. |
| `aspr_acpt_hour` | `category` | `Int64` | `HHMMSS` 형식의 시간은 숫자 연산이 가능하도록 `Int64` 정수형으로 관리합니다. |
| `askp1` | `object` | `Int64` | 가격 데이터는 숫자이므로, 결측치를 안전하게 처리하는 `Int64` 타입이 적합합니다. |
| `askp2` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp3` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp4` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp5` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp6` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp7` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp8` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp9` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp10` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp1` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp2` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp3` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp4` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp5` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp6` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp7` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp8` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp9` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp10` | `object` | `Int64` | 가격 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn1` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn2` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn3` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn4` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn5` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn6` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn7` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn8` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn9` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `askp_rsqn10` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn1` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn2` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn3` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn4` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn5` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn6` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn7` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn8` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn9` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `bidp_rsqn10` | `object` | `Int64` | 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `total_askp_rsqn`| `object` | `Int64` | 총 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `total_bidp_rsqn`| `object` | `Int64` | 총 잔량 데이터는 숫자이므로, `Int64` 타입이 적합합니다. |
| `ntby_aspr_rsqn`| `object` | `Int64` | 순매수 잔량은 음수일 수 있는 숫자이므로, `Int64` 타입이 적합합니다. |
| `new_mkop_cls_code`| `category` | `category` | '31' 등 몇 가지 코드로 구성된 범주형 데이터이므로 `category`가 효율적입니다. |

In [14]:
cols_to_check = []

# 1. 모든 컬럼을 숫자 타입으로 먼저 변환
df[cols_to_check] = df[cols_to_check].apply(pd.to_numeric, errors='coerce')


# 2. 각 컬럼별로 정수 형태 데이터의 비율을 계산하는 함수를 적용
def get_integer_like_ratio(series: pd.Series) -> float:
  """
  Series의 유효한 값(NaN 제외) 중, 정수 형태인 값의 비율을 계산합니다.
  """
  # NaN 값을 제외한 데이터만 추출
  series_without_na = series.dropna()
  
  # 유효한 데이터가 없는 경우, 1.0 (100%) 반환
  if series_without_na.empty:
    return 1.0
    
  # (정수 형태인 값의 개수) / (전체 유효 데이터의 개수)
  integer_like_count = (series_without_na % 1 == 0).sum()
  total_valid_count = len(series_without_na)
  
  return integer_like_count / total_valid_count

# --- 결과 확인 ---
integer_like_ratio_result = df[cols_to_check].apply(get_integer_like_ratio)
print(integer_like_ratio_result.round(2))

Series([], dtype: float64)

In [15]:
dtype_map = {
    'category': ['ticker', 'new_mkop_cls_code'],
    'Int64': [
        'aspr_acpt_hour', 
        'askp1', 'askp2', 'askp3', 'askp4', 'askp5', 'askp6', 'askp7', 'askp8', 'askp9', 'askp10',
        'bidp1', 'bidp2', 'bidp3', 'bidp4', 'bidp5', 'bidp6', 'bidp7', 'bidp8', 'bidp9', 'bidp10',
        'askp_rsqn1', 'askp_rsqn2', 'askp_rsqn3', 'askp_rsqn4', 'askp_rsqn5', 'askp_rsqn6', 'askp_rsqn7', 'askp_rsqn8', 'askp_rsqn9', 'askp_rsqn10',
        'bidp_rsqn1', 'bidp_rsqn2', 'bidp_rsqn3', 'bidp_rsqn4', 'bidp_rsqn5', 'bidp_rsqn6', 'bidp_rsqn7', 'bidp_rsqn8', 'bidp_rsqn9', 'bidp_rsqn10',
        'total_askp_rsqn', 'total_bidp_rsqn', 'ntby_aspr_rsqn'
    ]
}

for dtype, cols in dtype_map.items():
  # DataFrame에 실제 존재하는 컬럼만 필터링
  valid_cols = [col for col in cols if col in final_df.columns]
  if not valid_cols:
    continue

  try:
    if dtype == 'Int64':
      for col in valid_cols:
        numeric_col = pd.to_numeric(final_df[col], errors='coerce')
        if not numeric_col.isnull().all():
          final_df[col] = numeric_col.astype('Int64')
    
    elif dtype == 'float64':
      final_df[valid_cols] = final_df[valid_cols].apply(pd.to_numeric, errors='coerce')

    elif dtype == 'datetime64':
      for col in valid_cols:
        final_df[col] = pd.to_datetime(final_df[col], errors='coerce')
    
    else: # 'category' 등 .astype()으로 처리 가능한 나머지 타입
      final_df[valid_cols] = final_df[valid_cols].astype(dtype)

  except (ValueError, TypeError) as e:
    print(f"⚠️ 경고: 컬럼 {valid_cols}을(를) '{dtype}'으로 변환 중 오류. 건너뜁니다. (에러: {e})")

In [16]:
final_df.head()

,ticker,aspr_acpt_hour,askp1,askp2,askp3,askp4,askp5,askp6,askp7,askp8,askp9,askp10,bidp1,bidp2,bidp3,bidp4,bidp5,bidp6,bidp7,bidp8,bidp9,bidp10,askp_rsqn1,askp_rsqn2,askp_rsqn3,askp_rsqn4,askp_rsqn5,askp_rsqn6,askp_rsqn7,askp_rsqn8,askp_rsqn9,askp_rsqn10,bidp_rsqn1,bidp_rsqn2,bidp_rsqn3,bidp_rsqn4,bidp_rsqn5,bidp_rsqn6,bidp_rsqn7,bidp_rsqn8,bidp_rsqn9,bidp_rsqn10,total_askp_rsqn,total_bidp_rsqn,ntby_aspr_rsqn,new_mkop_cls_code
0,000080,160000,19170,19180,19190,19200,19210,19220,19230,19240,19250,19260,19160,19150,19140,19130,19120,19110,19100,19090,19080,19070,2593,1470,254,181,25,135,3,1174,23,46,298,5086,1207,5708,5010,7074,5596,2932,5652,1119,5904,39682,33778,31
1,000100,160000,118600,118700,118800,118900,119000,119100,119200,119300,119400,119500,118500,118400,118300,118200,118100,118000,117900,117800,117700,117600,1110,2795,1710,5032,4668,2908,2231,1382,1584,7822,527,848,4620,3904,1700,2827,1878,1154,831,1650,31242,19939,-11303,31
2,000120,160000,84500,84600,84700,84800,84900,85000,85100,85200,85300,85400,84400,84300,84200,84100,84000,83900,83800,83700,83600,83500,528,260,645,176,10,41,230,170,10,73,340,96,545,477,1899,1709,762,699,216,404,2143,7147,5004,20
3,000150,160000,596000,597000,598000,599000,600000,601000,602000,603000,604000,605000,595000,594000,593000,592000,591000,590000,589000,588000,587000,586000,2847,2613,2392,2000,1843,3653,4486,540,531,2039,443,789,1742,2101,434,2129,481,263,176,3519,22944,12077,-10867,31
4,000210,160000,37550,37600,37650,37700,37800,37850,37900,37950,38000,38050,37500,37300,37250,37200,37150,37100,37050,37000,36950,36900,512,221,1153,1,312,9,288,318,8307,5121,180,198,342,1127,818,517,1444,1570,666,144,16242,7006,-9236,31

In [17]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 46 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ticker             200 non-null    category
 1   aspr_acpt_hour     200 non-null    Int64
 2   askp1              200 non-null    Int64
 3   askp2              200 non-null    Int64
 4   askp3              200 non-null    Int64
 5   askp4              200 non-null    Int64
 6   askp5              200 non-null    Int64
 7   askp6              200 non-null    Int64
 8   askp7              200 non-null    Int64
 9   askp8              200 non-null    Int64
 10  askp9              200 non-null    Int64
 11  askp10             200 non-null    Int64
 12  bidp1              200 non-null    Int64
 13  bidp2              200 non-null    Int64
 14  bidp3              200 non-null    Int64
 15  bidp4              200 non-null    Int64
 16  bidp5              200 non-null    Int64
 17  bidp6              200 non-null    Int64
 18  bidp7              200 non-null    Int64
 19  bidp8              200 non-null    Int64
 20  bidp9              200 non-null    Int64
 21  bidp10             200 non-null    Int64
 22  askp_rsqn1         200 non-null    Int64
 23  askp_rsqn2         200 non-null    Int64
 24  askp_rsqn3         200 non-null    Int64
 25  askp_rsqn4         200 non-null    Int64
 26  askp_rsqn5         200 non-null    Int64
 27  askp_rsqn6         200 non-null    Int64
 28  askp_rsqn7         200 non-null    Int64
 29  askp_rsqn8         200 non-null    Int64
 30  askp_rsqn9         200 non-null    Int64
 31  askp_rsqn10        200 non-null    Int64
 32  bidp_rsqn1         200 non-null    Int64
 33  bidp_rsqn2         200 non-null    Int64
 34  bidp_rsqn3         200 non-null    Int64
 35  bidp_rsqn4         200 non-null    Int64
 36  bidp_rsqn5         200 non-null    Int64
 37  bidp_rsqn6         200 non-null    Int64
 38  bidp_rsqn7         200 non-null    Int64
 39  bidp_rsqn8         200 non-null    Int64
 40  bidp_rsqn9         200 non-null    Int64
 41  bidp_rsqn10        200 non-null    Int64
 42  total_askp_rsqn    200 non-null    Int64
 43  total_bidp_rsqn    200 non-null    Int64
 44  ntby_aspr_rsqn     200 non-null    Int64
 45  new_mkop_cls_code  200 non-null    category
dtypes: Int64(44), category(2)
memory usage: 87.8 KB